var annotated =
[
    [ "AABB", "class_a_a_b_b.html", "class_a_a_b_b" ],
    [ "AABBLinkedList", "class_a_a_b_b_linked_list.html", "class_a_a_b_b_linked_list" ],
    [ "AABBNode", "class_a_a_b_b_node.html", "class_a_a_b_b_node" ],
    [ "bag", "structbag.html", "structbag" ],
    [ "Camera", "class_camera.html", "class_camera" ],
    [ "CameraMap", "class_camera_map.html", "class_camera_map" ],
    [ "camVec", "structcam_vec.html", "structcam_vec" ],
    [ "sf::SoundStream::Chunk", "structsf_1_1_sound_stream_1_1_chunk.html", "structsf_1_1_sound_stream_1_1_chunk" ],
    [ "sf::CircleShape", "classsf_1_1_circle_shape.html", "classsf_1_1_circle_shape" ],
    [ "sf::Clock", "classsf_1_1_clock.html", "classsf_1_1_clock" ],
    [ "Collision", "class_collision.html", "class_collision" ],
    [ "sf::Color", "classsf_1_1_color.html", "classsf_1_1_color" ],
    [ "Colour", "struct_colour.html", "struct_colour" ],
    [ "sf::Context", "classsf_1_1_context.html", "classsf_1_1_context" ],
    [ "sf::ContextSettings", "structsf_1_1_context_settings.html", "structsf_1_1_context_settings" ],
    [ "sf::ConvexShape", "classsf_1_1_convex_shape.html", "classsf_1_1_convex_shape" ],
    [ "coordinate", "structcoordinate.html", "structcoordinate" ],
    [ "sf::Shader::CurrentTextureType", "structsf_1_1_shader_1_1_current_texture_type.html", null ],
    [ "sf::Ftp::DirectoryResponse", "classsf_1_1_ftp_1_1_directory_response.html", "classsf_1_1_ftp_1_1_directory_response" ],
    [ "sf::Drawable", "classsf_1_1_drawable.html", "classsf_1_1_drawable" ],
    [ "Edge", "struct_edge.html", "struct_edge" ],
    [ "sf::Event", "classsf_1_1_event.html", "classsf_1_1_event" ],
    [ "Face", "struct_face.html", "struct_face" ],
    [ "face", "structface.html", "structface" ],
    [ "sf::Font", "classsf_1_1_font.html", "classsf_1_1_font" ],
    [ "sf::Ftp", "classsf_1_1_ftp.html", "classsf_1_1_ftp" ],
    [ "sf::GlResource", "classsf_1_1_gl_resource.html", "classsf_1_1_gl_resource" ],
    [ "sf::Glyph", "classsf_1_1_glyph.html", "classsf_1_1_glyph" ],
    [ "sf::Http", "classsf_1_1_http.html", "classsf_1_1_http" ],
    [ "ilError", "classil_error.html", "classil_error" ],
    [ "ilFilters", "classil_filters.html", "classil_filters" ],
    [ "ILimage", "struct_i_limage.html", "struct_i_limage" ],
    [ "ilImage", "classil_image.html", "classil_image" ],
    [ "ILinfo", "struct_i_linfo.html", "struct_i_linfo" ],
    [ "ILpal", "struct_i_lpal.html", "struct_i_lpal" ],
    [ "ILpointf", "struct_i_lpointf.html", "struct_i_lpointf" ],
    [ "ILpointi", "struct_i_lpointi.html", "struct_i_lpointi" ],
    [ "ilState", "classil_state.html", "classil_state" ],
    [ "ilValidate", "classil_validate.html", "classil_validate" ],
    [ "sf::Image", "classsf_1_1_image.html", "classsf_1_1_image" ],
    [ "sf::InputStream", "classsf_1_1_input_stream.html", "classsf_1_1_input_stream" ],
    [ "sf::IpAddress", "classsf_1_1_ip_address.html", "classsf_1_1_ip_address" ],
    [ "sf::Joystick", "classsf_1_1_joystick.html", "classsf_1_1_joystick" ],
    [ "sf::Event::JoystickButtonEvent", "structsf_1_1_event_1_1_joystick_button_event.html", "structsf_1_1_event_1_1_joystick_button_event" ],
    [ "sf::Event::JoystickConnectEvent", "structsf_1_1_event_1_1_joystick_connect_event.html", "structsf_1_1_event_1_1_joystick_connect_event" ],
    [ "sf::Event::JoystickMoveEvent", "structsf_1_1_event_1_1_joystick_move_event.html", "structsf_1_1_event_1_1_joystick_move_event" ],
    [ "sf::Keyboard", "classsf_1_1_keyboard.html", "classsf_1_1_keyboard" ],
    [ "sf::Event::KeyEvent", "structsf_1_1_event_1_1_key_event.html", "structsf_1_1_event_1_1_key_event" ],
    [ "sf::Listener", "classsf_1_1_listener.html", "classsf_1_1_listener" ],
    [ "sf::Ftp::ListingResponse", "classsf_1_1_ftp_1_1_listing_response.html", "classsf_1_1_ftp_1_1_listing_response" ],
    [ "Loader", "class_loader.html", "class_loader" ],
    [ "sf::Lock", "classsf_1_1_lock.html", "classsf_1_1_lock" ],
    [ "Material", "struct_material.html", "struct_material" ],
    [ "sf::Mouse", "classsf_1_1_mouse.html", "classsf_1_1_mouse" ],
    [ "sf::Event::MouseButtonEvent", "structsf_1_1_event_1_1_mouse_button_event.html", "structsf_1_1_event_1_1_mouse_button_event" ],
    [ "sf::Event::MouseMoveEvent", "structsf_1_1_event_1_1_mouse_move_event.html", "structsf_1_1_event_1_1_mouse_move_event" ],
    [ "sf::Event::MouseWheelEvent", "structsf_1_1_event_1_1_mouse_wheel_event.html", "structsf_1_1_event_1_1_mouse_wheel_event" ],
    [ "MTL", "class_m_t_l.html", "class_m_t_l" ],
    [ "sf::Music", "classsf_1_1_music.html", "classsf_1_1_music" ],
    [ "sf::Mutex", "classsf_1_1_mutex.html", "classsf_1_1_mutex" ],
    [ "sf::NonCopyable", "classsf_1_1_non_copyable.html", "classsf_1_1_non_copyable" ],
    [ "normal", "structnormal.html", "structnormal" ],
    [ "sf::Packet", "classsf_1_1_packet.html", "classsf_1_1_packet" ],
    [ "PlainLinkedList", "class_plain_linked_list.html", "class_plain_linked_list" ],
    [ "PlainNode", "class_plain_node.html", "class_plain_node" ],
    [ "points", "structpoints.html", "structpoints" ],
    [ "sf::Rect< T >", "classsf_1_1_rect.html", "classsf_1_1_rect" ],
    [ "sf::RectangleShape", "classsf_1_1_rectangle_shape.html", "classsf_1_1_rectangle_shape" ],
    [ "sf::RenderStates", "classsf_1_1_render_states.html", "classsf_1_1_render_states" ],
    [ "sf::RenderTarget", "classsf_1_1_render_target.html", "classsf_1_1_render_target" ],
    [ "sf::RenderTexture", "classsf_1_1_render_texture.html", "classsf_1_1_render_texture" ],
    [ "sf::RenderWindow", "classsf_1_1_render_window.html", "classsf_1_1_render_window" ],
    [ "sf::Http::Request", "classsf_1_1_http_1_1_request.html", "classsf_1_1_http_1_1_request" ],
    [ "sf::Ftp::Response", "classsf_1_1_ftp_1_1_response.html", "classsf_1_1_ftp_1_1_response" ],
    [ "sf::Http::Response", "classsf_1_1_http_1_1_response.html", "classsf_1_1_http_1_1_response" ],
    [ "sf::Shader", "classsf_1_1_shader.html", "classsf_1_1_shader" ],
    [ "sf::Shape", "classsf_1_1_shape.html", "classsf_1_1_shape" ],
    [ "ShayWorld", "class_shay_world.html", "class_shay_world" ],
    [ "sf::Event::SizeEvent", "structsf_1_1_event_1_1_size_event.html", "structsf_1_1_event_1_1_size_event" ],
    [ "sf::Socket", "classsf_1_1_socket.html", "classsf_1_1_socket" ],
    [ "sf::SocketSelector", "classsf_1_1_socket_selector.html", "classsf_1_1_socket_selector" ],
    [ "sf::Sound", "classsf_1_1_sound.html", "classsf_1_1_sound" ],
    [ "Sound", "class_sound.html", "class_sound" ],
    [ "sf::SoundBuffer", "classsf_1_1_sound_buffer.html", "classsf_1_1_sound_buffer" ],
    [ "sf::SoundBufferRecorder", "classsf_1_1_sound_buffer_recorder.html", "classsf_1_1_sound_buffer_recorder" ],
    [ "sf::SoundRecorder", "classsf_1_1_sound_recorder.html", "classsf_1_1_sound_recorder" ],
    [ "sf::SoundSource", "classsf_1_1_sound_source.html", "classsf_1_1_sound_source" ],
    [ "sf::SoundStream", "classsf_1_1_sound_stream.html", "classsf_1_1_sound_stream" ],
    [ "sf::Sprite", "classsf_1_1_sprite.html", "classsf_1_1_sprite" ],
    [ "sf::String", "classsf_1_1_string.html", "classsf_1_1_string" ],
    [ "sf::TcpListener", "classsf_1_1_tcp_listener.html", "classsf_1_1_tcp_listener" ],
    [ "sf::TcpSocket", "classsf_1_1_tcp_socket.html", "classsf_1_1_tcp_socket" ],
    [ "TexCoord", "struct_tex_coord.html", "struct_tex_coord" ],
    [ "sf::Text", "classsf_1_1_text.html", "classsf_1_1_text" ],
    [ "sf::Event::TextEvent", "structsf_1_1_event_1_1_text_event.html", "structsf_1_1_event_1_1_text_event" ],
    [ "sf::Texture", "classsf_1_1_texture.html", "classsf_1_1_texture" ],
    [ "TexturedPolygons", "class_textured_polygons.html", "class_textured_polygons" ],
    [ "sf::Thread", "classsf_1_1_thread.html", "classsf_1_1_thread" ],
    [ "priv::ThreadFunc", "structpriv_1_1_thread_func.html", "structpriv_1_1_thread_func" ],
    [ "priv::ThreadFunctor< T >", "structpriv_1_1_thread_functor.html", "structpriv_1_1_thread_functor" ],
    [ "priv::ThreadFunctorWithArg< F, A >", "structpriv_1_1_thread_functor_with_arg.html", "structpriv_1_1_thread_functor_with_arg" ],
    [ "sf::ThreadLocal", "classsf_1_1_thread_local.html", "classsf_1_1_thread_local" ],
    [ "sf::ThreadLocalPtr< T >", "classsf_1_1_thread_local_ptr.html", "classsf_1_1_thread_local_ptr" ],
    [ "priv::ThreadMemberFunc< C >", "structpriv_1_1_thread_member_func.html", "structpriv_1_1_thread_member_func" ],
    [ "sf::Time", "classsf_1_1_time.html", "classsf_1_1_time" ],
    [ "sf::Transform", "classsf_1_1_transform.html", "classsf_1_1_transform" ],
    [ "sf::Transformable", "classsf_1_1_transformable.html", "classsf_1_1_transformable" ],
    [ "sf::UdpSocket", "classsf_1_1_udp_socket.html", "classsf_1_1_udp_socket" ],
    [ "sf::Utf", "classsf_1_1_utf.html", null ],
    [ "sf::Utf< 16 >", "classsf_1_1_utf_3_0116_01_4.html", "classsf_1_1_utf_3_0116_01_4" ],
    [ "sf::Utf< 32 >", "classsf_1_1_utf_3_0132_01_4.html", "classsf_1_1_utf_3_0132_01_4" ],
    [ "sf::Utf< 8 >", "classsf_1_1_utf_3_018_01_4.html", "classsf_1_1_utf_3_018_01_4" ],
    [ "Vector", "struct_vector.html", "struct_vector" ],
    [ "sf::Vector2< T >", "classsf_1_1_vector2.html", "classsf_1_1_vector2" ],
    [ "sf::Vector3< T >", "classsf_1_1_vector3.html", "classsf_1_1_vector3" ],
    [ "sf::Vertex", "classsf_1_1_vertex.html", "classsf_1_1_vertex" ],
    [ "sf::VertexArray", "classsf_1_1_vertex_array.html", "classsf_1_1_vertex_array" ],
    [ "sf::VideoMode", "classsf_1_1_video_mode.html", "classsf_1_1_video_mode" ],
    [ "sf::View", "classsf_1_1_view.html", "classsf_1_1_view" ],
    [ "WFObject", "class_w_f_object.html", "class_w_f_object" ],
    [ "sf::Window", "classsf_1_1_window.html", "classsf_1_1_window" ],
    [ "zAABB", "classz_a_a_b_b.html", "classz_a_a_b_b" ],
    [ "zCamera", "classz_camera.html", "classz_camera" ],
    [ "zcamVec", "structzcam_vec.html", "structzcam_vec" ],
    [ "zInventory", "classz_inventory.html", "classz_inventory" ],
    [ "zKey", "classz_key.html", "classz_key" ],
    [ "zObject", "classz_object.html", "classz_object" ],
    [ "ZombieNight", "class_zombie_night.html", "class_zombie_night" ],
    [ "zPlayer", "classz_player.html", "classz_player" ],
    [ "zZombie", "classz_zombie.html", "classz_zombie" ]
];